name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      # 1
      - uses: actions/checkout@v1
      # 2
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
